### ISSUE TITLE
Future Enhancements

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_salesforce#12]
Evaluating modeling the final raw tables:

- Contact 
- contract
- Event 
- Lead
- Opp
- Opp history
- Opp line item
- product_2
- Task
- User
- location

**Comment by fivetran-kristin** [comment]
@mdimercurio - please comment in here with any more details you have or specific ideas as to what the final models could look like.

**Comment by mdimercurio** [comment]
list of models that we build from Salesforce data:
- Historical pipeline (daily/weekly/monthly), with breakdown per product
- LTV: this might be too custom to include in a package
- Targets achievements: to build a visualization like [this one](https://www.onlinesalesguidetip.com/step-by-step-capacity-planning-model-for-bdr-and-sales-team/)

**Comment by fivetran-joemarkiewicz** [comment]
Closing out this issue as it has been open for quite some time. We also have included the majority of the above mentioned tables in the package. Please feel free to open a new issue if you would like to discuss this further for a feature enhancement to this package.
