### ISSUE TITLE
BUG - Typo on README Model Descriptions

### ISSUE THREAD

**Issue by GLuft3** [fivetran/dbt_salesforce#17]
**Are you a current Fivetran customer?** 
George Luft, Hashmap, inc.  (Fivetran Partner)

**Describe the bug**

The model description says loses instead of losses.

**Steps to reproduce**
1. Go to 'README.md'
2. Scroll down to the Models table
3. See typo in model description

**Expected behavior**

Spelling should be corrected from "loses" to "losses"

**Project variables configuration**

N/A

**Package Version**

N/A

**Warehouse**
N/A

**Additional context**
 
N/A

**Screenshots**

N/A

**Please indicate the level of urgency** 

Not urgent.  Just cleanup.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [X] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-kristin** [comment]
Updated! Thanks for catching this.
