### ISSUE TITLE
FEATURE - Remove user_role table from package

### ISSUE THREAD

**Issue by MishaSapsay** [fivetran/dbt_salesforce#23]
**Are you a Fivetran customer?** 
Misha Sapsay, Data Solutions Architect at TripleLift

**Is your feature request related to a problem? Please describe.**
The Salesforce package uses the user_role table heavily in its models. Our Snowflake schema doesn't have this table, so the associated models fail.

**Describe the solution you'd like**
It would be great to be able to exclude specific source tables and have the package automatically remove references to those tables.

**Describe alternatives you've considered**
Currently, set stg_salesforce__user_role and salesforce__manager_performance to enabled: false.

This however throws warnings about tests that cannot be run now

**Additional context**

**Please indicate the level of urgency and business impact of this request** 
Not critical, but certainly would be a nice-to-have. The current alternative seems sufficient for this to work for our instance.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ X] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @MishaSapsay thanks so much for opening this feature request!

This should be a relatively easy fix. I have added it to our next sprint. Someone from our team will post back here with an update in the next couple days 😄

**Comment by fivetran-joemarkiewicz** [comment]
The latest release of this package integrates this feature. Closing the FR.
