### ISSUE TITLE
[Bug] Update readme with new models to disable

### ISSUE THREAD

**Issue by fivetran-reneeli** [fivetran/dbt_salesforce#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The readme currently only lists one model under the [Disabling Models section](https://github.com/fivetran/dbt_salesforce/blob/6bdfbec7485470f3b819013c218996ea3b8d3c5f/README.md#disabling-models).

There are several listed in the [dbt_project.yml](https://github.com/fivetran/dbt_salesforce/blob/6bdfbec7485470f3b819013c218996ea3b8d3c5f/dbt_project.yml#L39-L45).

We should update the documentation. Thank you @artyom-vasilyev for noticing this!

### Expected behavior

Update readme with the rest of the models that can be disabled

### dbt Project configurations

n/a

### Package versions

n/a

### What database are you using dbt with?

bigquery

### dbt Version

n/a

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-catfritz** [comment]
This has been addressed in release v0.7.2. Closing this issue!
