### ISSUE TITLE
[Bug] Date spine model is inconsistent when selecting opportunity and lead for min/max

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_salesforce#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

In the int_salesforce__date_spine model there is logic to select the min and max start and end times in order to generate the date spine. There is [logic in place](https://github.com/fivetran/dbt_salesforce/blob/099a9524ef3252594f88fd9e0292ed250e3c7939/models/intermediate/int_salesforce__date_spine.sql#L2-L11) to use either the `lead` or `opportunity` sources when generating the min date in the spine. However, this same conditional is not also used for the [end date logic](https://github.com/fivetran/dbt_salesforce/blob/099a9524ef3252594f88fd9e0292ed250e3c7939/models/intermediate/int_salesforce__date_spine.sql#L28-L30).

This usually will not be an issue if a user still has the `opportunity` source. However, if the opportunity source is not present then this model will fail. We should update the logic in the model to ensure it may succeed or be disabled if the `opportunity` model is not present in the source.

### Relevant error log or model output

```shell
Compilation Error in model.salesforce.salesforce__daily_activity, caused by compilation error in referenced ephemeral model model.salesforce.int_salesforce__date_spine
```

### Expected behavior

The model either succeeds as expected, or is disabled if the `opportunity` model is not present

### dbt Project configurations

```yml
vars:
   salesforce__lead_enabled: true
```

### Package versions

v1.0.0

### What database are you using dbt with?

postgres, redshift, snowflake, bigquery, databricks

### dbt Version

1.6.0

### Additional Context

We should consider if swapping to use the `lead` table when the `salesforce__lead_enabled` is enabled is the best approach. This may not be the approach we want to take. This should be thought through and evaluated before changes are applied.

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-jamie** [comment]
in v1.0.1
