### ISSUE TITLE
Upgrade to use a newer version of dbt utils

### ISSUE THREAD

**Issue by jcbmllgn** [fivetran/dbt_salesforce#9]
Right now this package relies on version 0.3.0 of dbt utils (link to the [packages.yml file](https://github.com/fivetran/dbt_salesforce/blob/master/packages.yml)).

**Comment by fivetran-kristin** [comment]
Hi @jcbmllgn - We'll be upgrading all of our packages to require dbt version > 0.18.0 and dbt utils >= 0.6.0 this week. Stay tuned for a new release.

**Comment by jcbmllgn** [comment]
Thanks for the updated @fivetran-kristin 🙌

**Comment by fivetran-kristin** [comment]
@jcbmllgn A fix for this has been pushed.  Please upgrade to version 0.2.0!
